modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/lingyunmo/EdiblePotionsMod/issues"
license = "MIT"

[[mods]]
modId = "ediblepotions"
version = "${version}"
displayName = "Edible Potions"
authors = "lingyunmo"
# 这里的 logoFile 对应 forge/src/main/resources/ 下的路径
logoFile = "assets/ediblepotions/icon.png"
description = '''
Edible Potions adds an Infusion Table to Minecraft, allowing you to infuse food with various potion effects.
Create powerful items like Night Vision Apples or Speed Beef!
Supports full automation with hoppers.
'''

[[dependencies.ediblepotions]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ediblepotions]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ediblepotions]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"